apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
      - name: superset
        image: apache/superset:latest
        ports:
        - containerPort: 8088
          protocol: TCP
        env:
        - name: SUPERSET_WEBSERVER_PORT
          value: "8088"
        - name: SUPERSET_LOAD_EXAMPLES
          value: "yes"
        - name: SUPERSET_SECRET_KEY
          value: "thisISaSECRET_1234"
